### ISSUE TITLE
Strive from hackage tarball fails its HLint test suite

### ISSUE THREAD

**Issue by DanBurton** [tfausak/strive#104]
How to reproduce:

* stack unpack strive-2.2.0
* add the following stack.yaml:
```
resolver: lts-5.8
packages:
- '.'
extra-deps:
- gpolyline-0.1.0.1
```
* stack test

I'm disabling the test suite on the stackage build server.

**Comment by tfausak** [comment]
Sorry about that! I removed the HLint test suite in eeb71424fb1cd66dfabac9e9bca2b761a445fa8b. [Version 2.2.1](https://github.com/tfausak/strive/compare/v2.2.0...2.2.1), which I released this morning, doesn't have that test suite.

**Comment by DanBurton** [comment]
Cool, thanks for the quick response!
