### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by TheNiceGuy** [tfausak/strive#106]
Hi, I'm trying to install your package using `cabal install strive` on Archlinux, but it fails.
```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: strive-2.2.2 (user goal)
trying: base-4.9.0.0/installed-4.9... (dependency of strive-2.2.2)
next goal: transformers (dependency of strive-2.2.2)
rejecting: transformers-0.5.2.0/installed-0.5..., transformers-0.5.2.0,
transformers-0.5.1.0, transformers-0.5.0.1, transformers-0.5.0.0 (conflict:
strive => transformers>=0.3 && <0.5)
rejecting: transformers-0.4.3.0, transformers-0.4.2.0 (conflict:
base==4.9.0.0/installed-4.9..., transformers => base>=2 && <4.9)
rejecting: transformers-0.4.1.0, transformers-0.3.0.0 (conflict:
base==4.9.0.0/installed-4.9..., transformers => base>=2 && <4.8 || >=1.0 &&
<2)
rejecting: transformers-0.2.2.1, transformers-0.2.1.0, transformers-0.2.0.0,
transformers-0.1.4.0, transformers-0.1.3.0, transformers-0.1.1.0,
transformers-0.1.0.1, transformers-0.0.1.0, transformers-0.0.0.0,
transformers-0.5.0.2 (conflict: strive => transformers>=0.3 && <0.5)
rejecting: transformers-0.4.0.0 (conflict: base==4.9.0.0/installed-4.9...,
transformers => base>=2 && <4.8 || >=1.0 && <2)
rejecting: transformers-0.2.2.0, transformers-0.1.0.0 (conflict: strive =>
transformers>=0.3 && <0.5)
Dependency tree exhaustively searched.
```
I'm not sure if it is a `strive` bug. I'm still learning Haskell. Thanks.

**Comment by tfausak** [comment]
Thanks for reporting this! You're using GHC 8, which I added support for in dc3185670261b0765a46ff52a7b47a486f6336c8. Unfortunately I didn't release a new version with those changes. Cabal is trying to install an old version that doesn't work, as you found out.

**Comment by tfausak** [comment]
You should be able to install [version 3.0.0](http://hackage.haskell.org/package/strive-3.0.0) now.

**Comment by liskin** [comment]
Are you sure dropping support for 7.10 is a good idea? GHC 8 is known to produce space leaks in xmonad, so it's not likely to end up in distros for... months. I, for one, am reverting https://github.com/tfausak/strive/commit/dc3185670261b0765a46ff52a7b47a486f6336c8 for whatever I'm doing with strive.

**Comment by tfausak** [comment]
If you want to continue using GHC < 8, you can use Strive < 3.

**Comment by TheNiceGuy** [comment]
Thank you very much. The installation worked.
