### ISSUE TITLE
TokenExchangeResponse should have AthleteSummary rather than AthleteDetailed

### ISSUE THREAD

**Issue by drdo** [tfausak/strive#107]
The response from Strava of a token exchange contains a summary representation of the athlete, rather than a detailed one.

As documented in http://strava.github.io/api/v3/oauth/#post-token .

**Comment by tfausak** [comment]
Thanks for reporting this issue! This should be a simple fix.

**Comment by tfausak** [comment]
Should be fixed on master. Can you try it out before I release a new version?

**Comment by drdo** [comment]
Seems to work.

In the meantime I had been using a workaround exactly like the commit you did, so it should be fine.
