### ISSUE TITLE
Expose variants that return `Response`

### ISSUE THREAD

**Issue by parsonsmatt** [tfausak/strive#113]
I'm working on an application that uses `strive` to import an athlete's bike rides. I will need to handle rate limiting concerns which are communicated via the [`-X-Rate-Limit` headers](https://developers.strava.com/docs/#rate-limiting). These are not available since the library returns only the response body in a successful request.

A work-around is to request like mad, and then check the `Left (Response { responseCode = 429, .. }` pattern and implement the back-off there.

**Comment by tfausak** [comment]
Sounds reasonable! I haven’t thought about this library in a while. It might take me some time to get up to speed and add this feature.

**Comment by liskin** [comment]
Hey @parsonsmatt, your application seems related to mine: https://github.com/liskin/strava-gear
It's not very user-friendly and currently it's really difficult to get working due to Strava having changed the way their oauth works and neither me nor @tfausak nor anyone else having time to adapt strive, but it might give you some inspiration. Feel free to contact me if you want to chat about it.

**Comment by parsonsmatt** [comment]
@tfausak No worries - I'll see about putting together a PR sometime soon for the feature.

@liskin Very cool! Do you mean that `strive` no longer works with Strava's OAuth stuff?

**Comment by liskin** [comment]
@parsonsmatt Well, it does, just not as well as it used to. Auth tokens used to have no expiration, so you could get one and use it. Now they're limited to a few minutes and then you need to refresh them, and this mechanism isn't implemented in strive. But maybe I was supposed to use a separate oauth library to handle this for me, I don't know, the project never got to a sufficiently advanced state so I just grab these tokens manually. :-)

Anyway, there's one fix that you do need: https://github.com/liskin/strive/commit/12b22a71f445b1bb0a9262b8457354560391ec69

**Comment by tfausak** [comment]
Gentle nudge: This issue has been open for a few months. Is this still something you need? If so, I can try to set aside some time to work on it.

**Comment by parsonsmatt** [comment]
I haven't had time to work on the project that required this. The OAuth pattern was a sufficient wrench in my gears that I haven't decided how I want to approach it. Feel free to close it out - it can be re-opened if anyone needs it again or you decide to implement it for your own needs.
