### ISSUE TITLE
Strava API sometimes returns empty array for LatLng

### ISSUE THREAD

**Issue by drdo** [tfausak/strive#115]
I've run into an issue where the Strava API sometimes returns `[]` for a `LatLng` when using endpoint `/athlete/activities`.
This is out of spec according to [LatLng](https://developers.strava.com/docs/reference/#api-models-LatLng).

Even so, it would be useful to support this undocumented behaviour as otherwise the library cannot be used in practice.

This should be a case of changing the parse behaviour and yielding `Nothing` when a `LatLng` field comes as `[]`.
I can see two solutions:
  1. Create a new type for a `LatLng` rather than use `(Double, Double)` in `ActivitySummary` and `ActivityDetailed`
  2. Keep the same `Maybe (Double, Double)` type

Solution 2 has the advantage of being backwards compatible but requires implementing the `FromJSON` instance
by hand.

Solution 1 can still take advantage of the TH automatic derivation but breaks compatibility.

In my opinion the correct solution is number 2 but I'd like to see what you think.
In either case I can implement this and submit a PR.

**Comment by tfausak** [comment]
I agree, option 2 seems like the best choice. It's a bummer that the API doesn't match the documentation. And it's unfortunate that the activity types won't be able to use derived instances. But it should be easy enough to turn both `null` and `[]` into `Nothing`.

**Comment by tfausak** [comment]
Fixed by #116.
