### ISSUE TITLE
getCurrentActivity Fails

### ISSUE THREAD

**Issue by MarcusWalz** [tfausak/strive#82]
It seems to be broken wherever activities is being refrenced. Perhaps it's an API change.

```haskell
main = do
   client <- buildClient "...token..."
   acts <- getCurrentActivities client $ with
    [ set page 1
     , set perPage 2
    ]
    print acts
```
Outputs Left "empty"

**Comment by tfausak** [comment]
Thank you for reporting this bug! I'll take a look at it soon. I suspect I'm expecting a field to be there and it's not.

**Comment by MarcusWalz** [comment]
Okay, I think I found it. The activity type needs to parsed as uppercase. For example "Run" instead of "run". I sent in a push request that should fix the issue.

This change never made it onto starva's changelog. 

Thanks for the library. I'll try to make it current in the next few days.

**Comment by tfausak** [comment]
did your pull request (#83) fix this issue?

**Comment by MarcusWalz** [comment]
I think so. The code above works now.
