### ISSUE TITLE
strive-0.6.2 distributes brokes Setup.hs file

### ISSUE THREAD

**Issue by peti** [tfausak/strive#88]
Environments that use `Setup.hs` to drive the build process cannot compile strive-0.6.2 because the module is called `Setup` instead of `Main`. Thus,  `ghc --make Setup` aborts:

    [1 of 1] Compiling Setup            ( Setup.hs, Setup.o )
    Warning: output was redirected with -o, but no output will be generated
    because there is no Main module.

A complete build log that shows the error in our automated build farm is available at http://hydra.cryp.to/build/480420/log/raw.

**Comment by tfausak** [comment]
Oops, sorry about that. I always use Cabal and didn't check `Setup.hs` after adding it in 3b174c292d8d53b981ec22d6f97aec7b4d0123b8.

**Comment by tfausak** [comment]
This should be fixed with version 0.7.1.

**Comment by peti** [comment]
Thank you!
